### ISSUE TITLE
easing.dampE not Working 

### ISSUE THREAD

**Issue by Asura-Ang** [adrianhajdin/project_threejs_ai#19]
When I am using 
```
easing.dampE(
    //   group.current.rotation,
    //   [state.pointer.y / 10, -state.pointer.x / 5, 0],
    //   0.25,
    //   delta
    // );
```
with 
``` <Environment preset="city" /> ```

Then I am getting this error
```
CameraRig.jsx?t=1686343803010:44  Uncaught TypeError: Cannot read properties of undefined (reading 'rotation')
    at Object.current (CameraRig.jsx?t=1686343803010:44:32)
    at render$1 (index-22ee0173.esm.js:1516:22)
    at loop (index-22ee0173.esm.js:1543:19)
```

and when I am commenting it the error is gone but the functionality is lost. Please help me with this issue I am stuck for 2 days now .

**Comment by SoumyaSubhrajit** [comment]
@Asura-Ang I think the `group.current` is the reading undefined what you can do is Double-check the code where the group is defined and make sure it is initialized correctly.
Manually you can do add test case by simpley iterate upon the object
If you still see the error again feel free to reach me in here.

**Comment by Ayman-aa** [comment]
I'm having almost the same issue, but the error is, "Uncaught TypeError: Cannot read properties of undefined (reading 'camera')".
everything seems normal, this is the code that I'm having:
`import React,{ useRef } from 'react';
import { useFrame } from '@react-three/fiber';
import { easing } from 'maath';
import { snapshot } from 'valtio';
import state from '../store';


const CameraRig = ({ children }) => {
  const group = useRef();
  const snap = snapshot(state);
  useFrame(({ state, delta }) => {
    const isBreakpoint = window.innerWidth <= 1260;
    const isMobile = window.innerWidth <= 600;
    
    // set the initial position of the model
    let targetPosition =[-0.4, 0, 2.5];
    if (snap.intro){
      if(isBreakpoint) targetPosition =[0, 0, 2];
      if(isMobile) targetPosition =[0, 0.2, 2.5];
    }else{
      if(isMobile) targetPosition =[0, 0, 2.5];
      else targetPosition =[0, 0, 2];
    }

    // set model camera position
    easing.damp3(state.camera.position, targetPosition, 0.25, delta);

    // set the model rotation smoothly    
    easing.dampE(
      group.current.rotation,
      [state.pointer.y / 10, -state.pointer.x / 5, 0],
      0.25,
      delta
    )
  });

  

  return <group ref={group}>{children}</group>
}

export default CameraRig`

**Comment by Ayman-aa** [comment]
I'm facing the same problem, if I deleted the useFrame, but with the useFrame, I'm having new problems, the same error but with pointer and camera undefined

**Comment by Ayman-aa** [comment]
I shut down my laptop yesterday and today the code is working, idk why or how but wow

**Comment by Ayman-aa** [comment]
I shut down my laptop yesterday and today the code is working, idk why or how but wow

**Comment by pradeepth02** [comment]
As soon as i click on ai full or ai logo button my screen goes white and i can see errors on the server terminal and even in inspect console.
![Screenshot (8)](https://github.com/adrianhajdin/project_threejs_ai/assets/115602871/3f35cfde-1f1a-4d50-9e24-91f7f745ab1e)
![Screenshot (9)](https://github.com/adrianhajdin/project_threejs_ai/assets/115602871/712d6f9b-014d-4565-a1fd
![Screenshot (10)](https://github.com/adrianhajdin/project_threejs_ai/assets/115602871/ce78e289-260d-481d-b3f4-38cfe98ab756)
-8d91beeafb68)
![Screenshot (11)](https://github.com/adrianhajdin/project_threejs_ai/assets/115602871/e8dba14d-2033-4c15-85ae-04699646b1ea)
Can someone please help me out with this....?

**Comment by zahranniyas** [comment]
I know this is late, but I came across this issue too. Please check if you have linked the ref to the <group> tag in the return. That should fix the issue
