### ISSUE TITLE
Anyone getting the same error? 

### ISSUE THREAD

**Issue by Jyotishmoy12** [adrianhajdin/project_threejs_ai#34]
project-threejs-ai-dalle-backend.onrender.com/api/v1/dalle:1     Failed to load resource: the server responded with a status of 500 ()
data:image/png;base…:1     Failed to load resource: net::ERR_INVALID_URL
index-a04e7605.js:3485 Error: Could not load data:image/png;base64,undefined: undefined)
    at index-a04e7605.js:3489:22964
    at HTMLImageElement.u (index-a04e7605.js:3455:187116)
Oy @ index-a04e7605.js:3485
index-a04e7605.js:40 Error: Could not load data:image/png;base64,undefined: undefined)
    at index-a04e7605.js:3489:22964
    at HTMLImageElement.u (index-a04e7605.js:3455:187116)
R_ @ index-a04e7605.js:40
index-a04e7605.js:40 Uncaught Error: Could not load data:image/png;base64,undefined: undefined)
    at index-a04e7605.js:3489:22964
    at HTMLImageElement.u (index-a04e7605.js:3455:187116)
index-a04e7605.js:3455 THREE.WebGLRenderer: Context Lost.

**Comment by adnan-samir** [comment]
Ig its beacaue of the key , your open ai account is expired , try making a new acc with diff email, no and generate a new key and apply it , it'll work fine .

**Comment by Nuellity** [comment]
it is actually not generating the base64 format of the image that you see "undefined" here "data:image/png;base64,undefined: undefined)". Check your openai api account if you have enough credit to make an api request, else add a payment method to your account. Alternatively you can try Tryleap ai api .

**Comment by Jyotishmoy12** [comment]
Hey everyone I have tried everything but it's still showing the same error.. Plsss helpppp.....
