### ISSUE TITLE
Anyone getting this error?

### ISSUE THREAD

**Issue by Jyotishmoy12** [adrianhajdin/project_threejs_ai#43]
Failed to load resource: the server responded with a status of 500 ()
data:image/png;base64,undefined:1     GET data:image/png;base64,undefined net::ERR_INVALID_URL
Image (async)
load @ three.module.js:41632
load @ three.module.js:41813
(anonymous) @ index-bb759d07.esm.js:1621
(anonymous) @ index-bb759d07.esm.js:1621
(anonymous) @ index-bb759d07.esm.js:1621
query @ index.js:34
suspend @ index.js:53
useLoader @ index-bb759d07.esm.js:1637
useTexture @ useTexture.js:8
Shirt @ Shirt.jsx:14
renderWithHooks @ react-reconciler.development.js:7363
updateFunctionComponent @ react-reconciler.development.js:11802
beginWork @ react-reconciler.development.js:13845
beginWork$1 @ react-reconciler.development.js:19513
performUnitOfWork @ react-reconciler.development.js:18686
workLoopSync @ react-reconciler.development.js:18597
renderRootSync @ react-reconciler.development.js:18565
performSyncWorkOnRoot @ react-reconciler.development.js:18183
flushSyncCallbacks @ react-reconciler.development.js:2936
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
2index-bb759d07.esm.js:1624 Uncaught Error: Could not load data:image/png;base64,undefined: undefined)
    at index-bb759d07.esm.js:1624:36
    at HTMLImageElement.onImageError (three.module.js:41607:19)
(anonymous) @ index-bb759d07.esm.js:1624
onImageError @ three.module.js:41607
VM22:1 The above error occurred in the <Shirt> component:

    at Shirt (http://127.0.0.1:5173/src/canvas/Shirt.jsx:25:16)
    at group
    at group
    at group
    at Center2 (http://127.0.0.1:5173/node_modules/.vite/deps/@react-three_drei.js?v=751429f1:112687:3)
    at group
    at CameraRig (http://127.0.0.1:5173/src/canvas/CameraRig.jsx:23:3)
    at Suspense
    at ErrorBoundary (http://127.0.0.1:5173/node_modules/.vite/deps/chunk-JTWUC76D.js?v=751429f1:16132:5)
    at FiberProvider (http://127.0.0.1:5173/node_modules/.vite/deps/chunk-JTWUC76D.js?v=751429f1:17860:21)
    at Provider (http://127.0.0.1:5173/node_modules/.vite/deps/chunk-JTWUC76D.js?v=751429f1:17462:3)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
eval @ VM22:1
logCapturedError @ react-reconciler.development.js:9747
callback @ react-reconciler.development.js:9815
callCallback @ react-reconciler.development.js:4279
commitUpdateQueue @ react-reconciler.development.js:4300
commitLayoutEffectOnFiber @ react-reconciler.development.js:14877
commitLayoutMountEffects_complete @ react-reconciler.development.js:16290
commitLayoutEffects_begin @ react-reconciler.development.js:16276
commitLayoutEffects @ react-reconciler.development.js:16214
commitRootImpl @ react-reconciler.development.js:18945
commitRoot @ react-reconciler.development.js:18811
finishConcurrentRender @ react-reconciler.development.js:17990
performConcurrentWorkOnRoot @ react-reconciler.development.js:17907
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
2index-bb759d07.esm.js:1624 Uncaught Error: Could not load data:image/png;base64,undefined: undefined)
    at index-bb759d07.esm.js:1624:36
    at HTMLImageElement.onImageError (three.module.js:41607:19)
(anonymous) @ index-bb759d07.esm.js:1624
onImageError @ three.module.js:41607
VM22:1 The above error occurred in the <ForwardRef(Canvas)> component:

    at Canvas (http://127.0.0.1:5173/node_modules/.vite/deps/chunk-JTWUC76D.js?v=751429f1:18002:3)
    at FiberProvider (http://127.0.0.1:5173/node_modules/.vite/deps/chunk-JTWUC76D.js?v=751429f1:17860:21)
    at CanvasWrapper
    at CanvasModel
    at main
    at App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
eval @ VM22:1
logCapturedError @ react-dom.development.js:18687
update.callback @ react-dom.development.js:18720
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23391
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25892
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:26923 Uncaught Error: Could not load data:image/png;base64,undefined: undefined)
    at index-bb759d07.esm.js:1624:36
    at HTMLImageElement.onImageError (three.module.js:41607:19)
(anonymous) @ index-bb759d07.esm.js:1624
onImageError @ three.module.js:41607
three.module.js:28071 THREE.WebGLRenderer: Context Lost.

**Comment by suryanshsingh2001** [comment]
Yes I am getting the same thing. Please respond you managed to resolve this bug

**Comment by celn-pro** [comment]
Try to get rid of that self closing environment tag I hope this resolves
```<ENVIRONMENT preset='city'  />

```

**Comment by Jyotishmoy12** [comment]
Still showing error!!

**Comment by mahimdashora** [comment]
getting same error
