### ISSUE TITLE
map-anisotropy={16} 

### ISSUE THREAD

**Issue by Nik-Nikhil** [adrianhajdin/project_threejs_ai#56]
Uncaught TypeError: Cannot read properties of undefined (reading 'anisotropy')
    at index-5bde93f1.esm.js:667:46
    at Array.reduce (<anonymous>)
    at applyProps$1 (index-5bde93f1.esm.js:667:25)
    at commitUpdate (index-5bde93f1.esm.js:297:12)
    at commitWork (react-reconciler.development.js:15871:13)
    at commitMutationEffectsOnFiber (react-reconciler.development.js:16204:9)
    at commitMutationEffects_complete (react-reconciler.development.js:16057:7)
    at commitMutationEffects_begin (react-reconciler.development.js:16046:7)
    at commitMutationEffects (react-reconciler.development.js:16016:3)
    at commitRootImpl (react-reconciler.development.js:18932:5)
react-reconciler.development.js:9747 The above error occurred in the <mesh> component:

    at mesh
    at Decal2 (http://localhost:5173/node_modules/.vite/deps/@react-three_drei.js?v=492ba6ea:83708:3)
    at mesh
    at group
    at Shirt (http://localhost:5173/src/canvas/Shirt.jsx?t=1701771056543:26:16)
    at group
    at group
    at group
    at Center2 (http://localhost:5173/node_modules/.vite/deps/@react-three_drei.js?v=492ba6ea:97717:3)
    at group
    at CameraRig (http://localhost:5173/src/canvas/CameraRig.jsx?t=1701764290657:23:22)
    at Suspense
    at ErrorBoundary (http://localhost:5173/node_modules/.vite/deps/chunk-XNSGC6M4.js?v=492ba6ea:16139:5)
    at FiberProvider (http://localhost:5173/node_modules/.vite/deps/chunk-XNSGC6M4.js?v=492ba6ea:17914:21)
    at Provider (http://localhost:5173/node_modules/.vite/deps/chunk-XNSGC6M4.js?v=492ba6ea:17512:3)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ react-reconciler.development.js:9747
2react-three-fiber.esm.js:145 Uncaught TypeError: Cannot read properties of undefined (reading 'anisotropy')
    at index-5bde93f1.esm.js:667:46
    at Array.reduce (<anonymous>)
    at applyProps$1 (index-5bde93f1.esm.js:667:25)
    at commitUpdate (index-5bde93f1.esm.js:297:12)
    at commitWork (react-reconciler.development.js:15871:13)
    at commitMutationEffectsOnFiber (react-reconciler.development.js:16204:9)
    at commitMutationEffects_complete (react-reconciler.development.js:16057:7)
    at commitMutationEffects_begin (react-reconciler.development.js:16046:7)
    at commitMutationEffects (react-reconciler.development.js:16016:3)
    at commitRootImpl (react-reconciler.development.js:18932:5)
react-dom.development.js:18687 The above error occurred in the <ForwardRef(Canvas)> component:

    at Canvas (http://localhost:5173/node_modules/.vite/deps/chunk-XNSGC6M4.js?v=492ba6ea:18058:3)
    at FiberProvider (http://localhost:5173/node_modules/.vite/deps/chunk-XNSGC6M4.js?v=492ba6ea:17914:21)
    at CanvasWrapper
    at CanvasModel
    at main
    at App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18687
react-dom.development.js:26923 Uncaught TypeError: Cannot read properties of undefined (reading 'anisotropy')
    at index-5bde93f1.esm.js:667:46
    at Array.reduce (<anonymous>)
    at applyProps$1 (index-5bde93f1.esm.js:667:25)
    at commitUpdate (index-5bde93f1.esm.js:297:12)
    at commitWork (react-reconciler.development.js:15871:13)
    at commitMutationEffectsOnFiber (react-reconciler.development.js:16204:9)
    at commitMutationEffects_complete (react-reconciler.development.js:16057:7)
    at commitMutationEffects_begin (react-reconciler.development.js:16046:7)
    at commitMutationEffects (react-reconciler.development.js:16016:3)
    at commitRootImpl (react-reconciler.development.js:18932:5)

**Comment by Nik-Nikhil** [comment]
in Backdrop.jsx ,there is scae={10} property instead of scale={10} in AccumulativeShadows tag , I don't know why it doesn't throw error.

**Comment by karthickkumarsm** [comment]
> Uncaught TypeError: Cannot read properties of undefined (reading 'anisotropy') at index-5bde93f1.esm.js:667:46 at Array.reduce () at applyProps$1 (index-5bde93f1.esm.js:667:25) at commitUpdate (index-5bde93f1.esm.js:297:12) at commitWork (react-reconciler.development.js:15871:13) at commitMutationEffectsOnFiber (react-reconciler.development.js:16204:9) at commitMutationEffects_complete (react-reconciler.development.js:16057:7) at commitMutationEffects_begin (react-reconciler.development.js:16046:7) at commitMutationEffects (react-reconciler.development.js:16016:3) at commitRootImpl (react-reconciler.development.js:18932:5) react-reconciler.development.js:9747 The above error occurred in the component:
> 
> ```
> at mesh
> at Decal2 (http://localhost:5173/node_modules/.vite/deps/@react-three_drei.js?v=492ba6ea:83708:3)
> at mesh
> at group
> at Shirt (http://localhost:5173/src/canvas/Shirt.jsx?t=1701771056543:26:16)
> at group
> at group
> at group
> at Center2 (http://localhost:5173/node_modules/.vite/deps/@react-three_drei.js?v=492ba6ea:97717:3)
> at group
> at CameraRig (http://localhost:5173/src/canvas/CameraRig.jsx?t=1701764290657:23:22)
> at Suspense
> at ErrorBoundary (http://localhost:5173/node_modules/.vite/deps/chunk-XNSGC6M4.js?v=492ba6ea:16139:5)
> at FiberProvider (http://localhost:5173/node_modules/.vite/deps/chunk-XNSGC6M4.js?v=492ba6ea:17914:21)
> at Provider (http://localhost:5173/node_modules/.vite/deps/chunk-XNSGC6M4.js?v=492ba6ea:17512:3)
> ```
> 
> React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary. logCapturedError @ react-reconciler.development.js:9747 2react-three-fiber.esm.js:145 Uncaught TypeError: Cannot read properties of undefined (reading 'anisotropy') at index-5bde93f1.esm.js:667:46 at Array.reduce () at applyProps$1 (index-5bde93f1.esm.js:667:25) at commitUpdate (index-5bde93f1.esm.js:297:12) at commitWork (react-reconciler.development.js:15871:13) at commitMutationEffectsOnFiber (react-reconciler.development.js:16204:9) at commitMutationEffects_complete (react-reconciler.development.js:16057:7) at commitMutationEffects_begin (react-reconciler.development.js:16046:7) at commitMutationEffects (react-reconciler.development.js:16016:3) at commitRootImpl (react-reconciler.development.js:18932:5) react-dom.development.js:18687 The above error occurred in the <ForwardRef(Canvas)> component:
> 
> ```
> at Canvas (http://localhost:5173/node_modules/.vite/deps/chunk-XNSGC6M4.js?v=492ba6ea:18058:3)
> at FiberProvider (http://localhost:5173/node_modules/.vite/deps/chunk-XNSGC6M4.js?v=492ba6ea:17914:21)
> at CanvasWrapper
> at CanvasModel
> at main
> at App
> ```
> 
> Consider adding an error boundary to your tree to customize error handling behavior. Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries. logCapturedError @ react-dom.development.js:18687 react-dom.development.js:26923 Uncaught TypeError: Cannot read properties of undefined (reading 'anisotropy') at index-5bde93f1.esm.js:667:46 at Array.reduce () at applyProps$1 (index-5bde93f1.esm.js:667:25) at commitUpdate (index-5bde93f1.esm.js:297:12) at commitWork (react-reconciler.development.js:15871:13) at commitMutationEffectsOnFiber (react-reconciler.development.js:16204:9) at commitMutationEffects_complete (react-reconciler.development.js:16057:7) at commitMutationEffects_begin (react-reconciler.development.js:16046:7) at commitMutationEffects (react-reconciler.development.js:16016:3) at commitRootImpl (react-reconciler.development.js:18932:5)

type mapAnisotropy={16} instead of map-anisotropy={16}

**Comment by softyanshi** [comment]
> > Uncaught TypeError: Cannot read properties of undefined (reading 'anisotropy') at index-5bde93f1.esm.js:667:46 at Array.reduce () at applyProps$1 (index-5bde93f1.esm.js:667:25) at commitUpdate (index-5bde93f1.esm.js:297:12) at commitWork (react-reconciler.development.js:15871:13) at commitMutationEffectsOnFiber (react-reconciler.development.js:16204:9) at commitMutationEffects_complete (react-reconciler.development.js:16057:7) at commitMutationEffects_begin (react-reconciler.development.js:16046:7) at commitMutationEffects (react-reconciler.development.js:16016:3) at commitRootImpl (react-reconciler.development.js:18932:5) react-reconciler.development.js:9747 The above error occurred in the component:
> > ```
> > at mesh
> > at Decal2 (http://localhost:5173/node_modules/.vite/deps/@react-three_drei.js?v=492ba6ea:83708:3)
> > at mesh
> > at group
> > at Shirt (http://localhost:5173/src/canvas/Shirt.jsx?t=1701771056543:26:16)
> > at group
> > at group
> > at group
> > at Center2 (http://localhost:5173/node_modules/.vite/deps/@react-three_drei.js?v=492ba6ea:97717:3)
> > at group
> > at CameraRig (http://localhost:5173/src/canvas/CameraRig.jsx?t=1701764290657:23:22)
> > at Suspense
> > at ErrorBoundary (http://localhost:5173/node_modules/.vite/deps/chunk-XNSGC6M4.js?v=492ba6ea:16139:5)
> > at FiberProvider (http://localhost:5173/node_modules/.vite/deps/chunk-XNSGC6M4.js?v=492ba6ea:17914:21)
> > at Provider (http://localhost:5173/node_modules/.vite/deps/chunk-XNSGC6M4.js?v=492ba6ea:17512:3)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary. logCapturedError @ react-reconciler.development.js:9747 2react-three-fiber.esm.js:145 Uncaught TypeError: Cannot read properties of undefined (reading 'anisotropy') at index-5bde93f1.esm.js:667:46 at Array.reduce () at applyProps$1 (index-5bde93f1.esm.js:667:25) at commitUpdate (index-5bde93f1.esm.js:297:12) at commitWork (react-reconciler.development.js:15871:13) at commitMutationEffectsOnFiber (react-reconciler.development.js:16204:9) at commitMutationEffects_complete (react-reconciler.development.js:16057:7) at commitMutationEffects_begin (react-reconciler.development.js:16046:7) at commitMutationEffects (react-reconciler.development.js:16016:3) at commitRootImpl (react-reconciler.development.js:18932:5) react-dom.development.js:18687 The above error occurred in the <ForwardRef(Canvas)> component:
> > ```
> > at Canvas (http://localhost:5173/node_modules/.vite/deps/chunk-XNSGC6M4.js?v=492ba6ea:18058:3)
> > at FiberProvider (http://localhost:5173/node_modules/.vite/deps/chunk-XNSGC6M4.js?v=492ba6ea:17914:21)
> > at CanvasWrapper
> > at CanvasModel
> > at main
> > at App
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Consider adding an error boundary to your tree to customize error handling behavior. Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries. logCapturedError @ react-dom.development.js:18687 react-dom.development.js:26923 Uncaught TypeError: Cannot read properties of undefined (reading 'anisotropy') at index-5bde93f1.esm.js:667:46 at Array.reduce () at applyProps$1 (index-5bde93f1.esm.js:667:25) at commitUpdate (index-5bde93f1.esm.js:297:12) at commitWork (react-reconciler.development.js:15871:13) at commitMutationEffectsOnFiber (react-reconciler.development.js:16204:9) at commitMutationEffects_complete (react-reconciler.development.js:16057:7) at commitMutationEffects_begin (react-reconciler.development.js:16046:7) at commitMutationEffects (react-reconciler.development.js:16016:3) at commitRootImpl (react-reconciler.development.js:18932:5)
> 
> type mapAnisotropy={16} instead of map-anisotropy={16}

still its not showing the tshirt
could u please help me....?

**Comment by softyanshi** [comment]
> Uncaught TypeError: Cannot read properties of undefined (reading 'anisotropy') at index-5bde93f1.esm.js:667:46 at Array.reduce () at applyProps$1 (index-5bde93f1.esm.js:667:25) at commitUpdate (index-5bde93f1.esm.js:297:12) at commitWork (react-reconciler.development.js:15871:13) at commitMutationEffectsOnFiber (react-reconciler.development.js:16204:9) at commitMutationEffects_complete (react-reconciler.development.js:16057:7) at commitMutationEffects_begin (react-reconciler.development.js:16046:7) at commitMutationEffects (react-reconciler.development.js:16016:3) at commitRootImpl (react-reconciler.development.js:18932:5) react-reconciler.development.js:9747 The above error occurred in the component:
> 
> ```
> at mesh
> at Decal2 (http://localhost:5173/node_modules/.vite/deps/@react-three_drei.js?v=492ba6ea:83708:3)
> at mesh
> at group
> at Shirt (http://localhost:5173/src/canvas/Shirt.jsx?t=1701771056543:26:16)
> at group
> at group
> at group
> at Center2 (http://localhost:5173/node_modules/.vite/deps/@react-three_drei.js?v=492ba6ea:97717:3)
> at group
> at CameraRig (http://localhost:5173/src/canvas/CameraRig.jsx?t=1701764290657:23:22)
> at Suspense
> at ErrorBoundary (http://localhost:5173/node_modules/.vite/deps/chunk-XNSGC6M4.js?v=492ba6ea:16139:5)
> at FiberProvider (http://localhost:5173/node_modules/.vite/deps/chunk-XNSGC6M4.js?v=492ba6ea:17914:21)
> at Provider (http://localhost:5173/node_modules/.vite/deps/chunk-XNSGC6M4.js?v=492ba6ea:17512:3)
> ```
> 
> React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary. logCapturedError @ react-reconciler.development.js:9747 2react-three-fiber.esm.js:145 Uncaught TypeError: Cannot read properties of undefined (reading 'anisotropy') at index-5bde93f1.esm.js:667:46 at Array.reduce () at applyProps$1 (index-5bde93f1.esm.js:667:25) at commitUpdate (index-5bde93f1.esm.js:297:12) at commitWork (react-reconciler.development.js:15871:13) at commitMutationEffectsOnFiber (react-reconciler.development.js:16204:9) at commitMutationEffects_complete (react-reconciler.development.js:16057:7) at commitMutationEffects_begin (react-reconciler.development.js:16046:7) at commitMutationEffects (react-reconciler.development.js:16016:3) at commitRootImpl (react-reconciler.development.js:18932:5) react-dom.development.js:18687 The above error occurred in the <ForwardRef(Canvas)> component:
> 
> ```
> at Canvas (http://localhost:5173/node_modules/.vite/deps/chunk-XNSGC6M4.js?v=492ba6ea:18058:3)
> at FiberProvider (http://localhost:5173/node_modules/.vite/deps/chunk-XNSGC6M4.js?v=492ba6ea:17914:21)
> at CanvasWrapper
> at CanvasModel
> at main
> at App
> ```
> 
> Consider adding an error boundary to your tree to customize error handling behavior. Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries. logCapturedError @ react-dom.development.js:18687 react-dom.development.js:26923 Uncaught TypeError: Cannot read properties of undefined (reading 'anisotropy') at index-5bde93f1.esm.js:667:46 at Array.reduce () at applyProps$1 (index-5bde93f1.esm.js:667:25) at commitUpdate (index-5bde93f1.esm.js:297:12) at commitWork (react-reconciler.development.js:15871:13) at commitMutationEffectsOnFiber (react-reconciler.development.js:16204:9) at commitMutationEffects_complete (react-reconciler.development.js:16057:7) at commitMutationEffects_begin (react-reconciler.development.js:16046:7) at commitMutationEffects (react-reconciler.development.js:16016:3) at commitRootImpl (react-reconciler.development.js:18932:5)

have u got the solution of it?

**Comment by karthickkumarsm** [comment]
> > > Uncaught TypeError: Cannot read properties of undefined (reading 'anisotropy') at index-5bde93f1.esm.js:667:46 at Array.reduce () at applyProps$1 (index-5bde93f1.esm.js:667:25) at commitUpdate (index-5bde93f1.esm.js:297:12) at commitWork (react-reconciler.development.js:15871:13) at commitMutationEffectsOnFiber (react-reconciler.development.js:16204:9) at commitMutationEffects_complete (react-reconciler.development.js:16057:7) at commitMutationEffects_begin (react-reconciler.development.js:16046:7) at commitMutationEffects (react-reconciler.development.js:16016:3) at commitRootImpl (react-reconciler.development.js:18932:5) react-reconciler.development.js:9747 The above error occurred in the component:
> > > ```
> > > at mesh
> > > at Decal2 (http://localhost:5173/node_modules/.vite/deps/@react-three_drei.js?v=492ba6ea:83708:3)
> > > at mesh
> > > at group
> > > at Shirt (http://localhost:5173/src/canvas/Shirt.jsx?t=1701771056543:26:16)
> > > at group
> > > at group
> > > at group
> > > at Center2 (http://localhost:5173/node_modules/.vite/deps/@react-three_drei.js?v=492ba6ea:97717:3)
> > > at group
> > > at CameraRig (http://localhost:5173/src/canvas/CameraRig.jsx?t=1701764290657:23:22)
> > > at Suspense
> > > at ErrorBoundary (http://localhost:5173/node_modules/.vite/deps/chunk-XNSGC6M4.js?v=492ba6ea:16139:5)
> > > at FiberProvider (http://localhost:5173/node_modules/.vite/deps/chunk-XNSGC6M4.js?v=492ba6ea:17914:21)
> > > at Provider (http://localhost:5173/node_modules/.vite/deps/chunk-XNSGC6M4.js?v=492ba6ea:17512:3)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary. logCapturedError @ react-reconciler.development.js:9747 2react-three-fiber.esm.js:145 Uncaught TypeError: Cannot read properties of undefined (reading 'anisotropy') at index-5bde93f1.esm.js:667:46 at Array.reduce () at applyProps$1 (index-5bde93f1.esm.js:667:25) at commitUpdate (index-5bde93f1.esm.js:297:12) at commitWork (react-reconciler.development.js:15871:13) at commitMutationEffectsOnFiber (react-reconciler.development.js:16204:9) at commitMutationEffects_complete (react-reconciler.development.js:16057:7) at commitMutationEffects_begin (react-reconciler.development.js:16046:7) at commitMutationEffects (react-reconciler.development.js:16016:3) at commitRootImpl (react-reconciler.development.js:18932:5) react-dom.development.js:18687 The above error occurred in the <ForwardRef(Canvas)> component:
> > > ```
> > > at Canvas (http://localhost:5173/node_modules/.vite/deps/chunk-XNSGC6M4.js?v=492ba6ea:18058:3)
> > > at FiberProvider (http://localhost:5173/node_modules/.vite/deps/chunk-XNSGC6M4.js?v=492ba6ea:17914:21)
> > > at CanvasWrapper
> > > at CanvasModel
> > > at main
> > > at App
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Consider adding an error boundary to your tree to customize error handling behavior. Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries. logCapturedError @ react-dom.development.js:18687 react-dom.development.js:26923 Uncaught TypeError: Cannot read properties of undefined (reading 'anisotropy') at index-5bde93f1.esm.js:667:46 at Array.reduce () at applyProps$1 (index-5bde93f1.esm.js:667:25) at commitUpdate (index-5bde93f1.esm.js:297:12) at commitWork (react-reconciler.development.js:15871:13) at commitMutationEffectsOnFiber (react-reconciler.development.js:16204:9) at commitMutationEffects_complete (react-reconciler.development.js:16057:7) at commitMutationEffects_begin (react-reconciler.development.js:16046:7) at commitMutationEffects (react-reconciler.development.js:16016:3) at commitRootImpl (react-reconciler.development.js:18932:5)
> > 
> > 
> > type mapAnisotropy={16} instead of map-anisotropy={16}
> 
> still its not showing the tshirt could u please help me....?

Yeah sure try to update your node version to the latest and try using mapAnisotropy={16}

**Comment by Sam-Aklan** [comment]
replacing "map-anisotropy" with "anisotropy" works for me
