### ISSUE TITLE
After ai logo clicked the page get blank and shows CORS error even though I have used CORS .

### ISSUE THREAD

**Issue by aakankshaverma42** [adrianhajdin/project_threejs_ai#64]
**This is the error which I am facing please help me !!**

localhost/:1  Access to image at 'https://oaidalleapiprodscus.blob.core.windows.net/private/org-6yw0lVSwCdRTujUZrpbDhK9s/user-DX1ZWENfPZsJa9hU8BzqQwq0/img-020DjAgWaY5Lp8EQ3tj8taAP.png?st=2024-03-22T08%3A42%3A09Z&se=2024-03-22T10%3A42%3A09Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2024-03-21T21%3A07%3A05Z&ske=2024-03-22T21%3A07%3A05Z&sks=b&skv=2021-08-06&sig=5XL6FKiuUc520hwPbTIM81dOqyrly845bVzr%2B2xaA14%3D' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
img-020DjAgWaY5Lp8EQ3tj8taAP.png:1 
        
        
        Failed to load resource: net::ERR_FAILED
2index.js:26  Uncaught Error: Could not load https://oaidalleapiprodscus.blob.core.windows.net/private/org-6yw0lVSwCdRTujUZrpbDhK9s/user-DX1ZWENfPZsJa9hU8BzqQwq0/img-020DjAgWaY5Lp8EQ3tj8taAP.png?st=2024-03-22T08%3A42%3A09Z&se=2024-03-22T10%3A42%3A09Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2024-03-21T21%3A07%3A05Z&ske=2024-03-22T21%3A07%3A05Z&sks=b&skv=2021-08-06&sig=5XL6FKiuUc520hwPbTIM81dOqyrly845bVzr%2B2xaA14%3D: undefined
    at index-e6b5343a.esm.js:1667:36
    at HTMLImageElement.onImageError (three.module.js:44255:19)
react-reconciler.development.js:9747  The above error occurred in the <Shirt> component:

    at Shirt (http://localhost:5173/src/canvas/Shirt.jsx:26:16)
    at group
    at group
    at group
    at Center2 (http://localhost:5173/node_modules/.vite/deps/@react-three_drei.js?v=cd9df346:91128:3)
    at group
    at CameraRig (http://localhost:5173/src/canvas/CameraRig.jsx:23:22)
    at Suspense
    at ErrorBoundary (http://localhost:5173/node_modules/.vite/deps/chunk-4ZFGV7ZP.js?v=cd9df346:16139:5)
    at FiberProvider (http://localhost:5173/node_modules/.vite/deps/chunk-4ZFGV7ZP.js?v=cd9df346:17915:21)
    at Provider (http://localhost:5173/node_modules/.vite/deps/chunk-4ZFGV7ZP.js?v=cd9df346:17513:3)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ react-reconciler.development.js:9747
2react-three-fiber.esm.js:145  Uncaught Error: Could not load https://oaidalleapiprodscus.blob.core.windows.net/private/org-6yw0lVSwCdRTujUZrpbDhK9s/user-DX1ZWENfPZsJa9hU8BzqQwq0/img-020DjAgWaY5Lp8EQ3tj8taAP.png?st=2024-03-22T08%3A42%3A09Z&se=2024-03-22T10%3A42%3A09Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2024-03-21T21%3A07%3A05Z&ske=2024-03-22T21%3A07%3A05Z&sks=b&skv=2021-08-06&sig=5XL6FKiuUc520hwPbTIM81dOqyrly845bVzr%2B2xaA14%3D: undefined
    at index-e6b5343a.esm.js:1667:36
    at HTMLImageElement.onImageError (three.module.js:44255:19)
react-dom.development.js:18687  The above error occurred in the <ForwardRef(Canvas)> component:

    at Canvas (http://localhost:5173/node_modules/.vite/deps/chunk-4ZFGV7ZP.js?v=cd9df346:18059:3)
    at FiberProvider (http://localhost:5173/node_modules/.vite/deps/chunk-4ZFGV7ZP.js?v=cd9df346:17915:21)
    at CanvasWrapper
    at CanvasModel
    at main
    at App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18687
react-dom.development.js:26923  Uncaught Error: Could not load https://oaidalleapiprodscus.blob.core.windows.net/private/org-6yw0lVSwCdRTujUZrpbDhK9s/user-DX1ZWENfPZsJa9hU8BzqQwq0/img-020DjAgWaY5Lp8EQ3tj8taAP.png?st=2024-03-22T08%3A42%3A09Z&se=2024-03-22T10%3A42%3A09Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2024-03-21T21%3A07%3A05Z&ske=2024-03-22T21%3A07%3A05Z&sks=b&skv=2021-08-06&sig=5XL6FKiuUc520hwPbTIM81dOqyrly845bVzr%2B2xaA14%3D: undefined
    at index-e6b5343a.esm.js:1667:36
    at HTMLImageElement.onImageError (three.module.js:44255:19)

**Comment by aakankshaverma42** [comment]
Error

**Comment by GIT-Gizmo** [comment]
Can you post the code?

**Comment by aakankshaverma42** [comment]
![image](https://github.com/adrianhajdin/project_threejs_ai/assets/92093809/b8a5b29c-6873-4eee-87f8-099691324d9e)
![image](https://github.com/adrianhajdin/project_threejs_ai/assets/92093809/d5203d1b-4cdb-4a71-8832-793adb15ce96)
![image](https://github.com/adrianhajdin/project_threejs_ai/assets/92093809/5c373248-5407-48c1-bd36-0dafda043994)
these are my code please help and let me know my mistakes.

**Comment by aakankshaverma42** [comment]
> Can you post the code?

i have posted my code please see it and let me know my mistake

**Comment by GIT-Gizmo** [comment]
Do you have a ChatGPT or DAL-E subscription?

**Comment by Sumeyya-ali** [comment]
> Do you have a ChatGPT or DAL-E subscription?

Is there new code to use Dal-e? i upgraded to paid account in openai. but dont know if the dall-e code in this project is outdated or not. can you help me out asap please.

**Comment by GIT-Gizmo** [comment]
> > Do you have a ChatGPT or DAL-E subscription?
> 
> Is there new code to use Dal-e? i upgraded to paid account in openai. but dont know if the dall-e code in this project is outdated or not. can you help me out asap please.

Yeah, I believe there's a new way to use Dall-E api since this video was released. I can't remember where I saw it though.
